Group filter parameters
This fixes an API error caused by any other parameter in between filter parameters.

Reference: https://forums.developer.ebay.com/questions/14689/error-value-is-required-for-item-filter-listing-ty.html

> Error: Value is required for item filter

> You're putting sortOrder in between two itemFilter parameters. Put the item filters together, in order. Move sortOrder to a different position.